language: c
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq autotools-dev autoconf automake libtool libssl-dev liburcu-dev flex bison ragel pkg-config texinfo texlive lcov
  - sudo pip install cpp-coveralls --use-mirrors
before_script:
  - autoreconf -fi
script:
  - ./configure --enable-code-coverage && make && make -k check
after_success:
  - coveralls --exclude zscanner/ --exclude tests/ --exclude src/cf-lex.l --exclude src/cf-parse.y --exclude src/scanner_body.rl --exclude src/scanner.c --exclude src/functions.c --exclude src/loader.c --exclude src/error.c --exclude src/scanner.rl --exclude src/allocator.h --build-root ./src/
